In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

In [3]:
torch.__version__

'0.4.0'

Construct a 5x3 matrix, uninitialized:



In [4]:
x = torch.ones(5, 3)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


Construct a randomly initialized matrix:



In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.2106,  0.6070,  0.2580],
        [ 0.0361,  0.0040,  0.3426],
        [ 0.6419,  0.8679,  0.5083],
        [ 0.5083,  0.2580,  0.2070],
        [ 0.0883,  0.3003,  0.5404]])


Construct a matrix filled zeros and of dtype long:



In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


Construct a tensor directly from data:



In [14]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


or create a tensor basing on existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [16]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 1.3563,  0.0317,  0.8930],
        [ 0.2144, -0.9887,  2.5370],
        [ 0.5389, -1.5360, -1.0414],
        [ 2.0580, -0.0040,  0.6831],
        [-1.6464,  0.3053, -0.8540]])


Get its size:



In [17]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [18]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.0430,  0.8754,  1.0142],
        [ 0.3666, -0.9551,  3.2764],
        [ 1.4205, -1.1513, -0.0960],
        [ 2.6366,  0.1989,  0.7589],
        [-0.7611,  0.5044, -0.6390]])


Addition: syntax 2



In [19]:
print(torch.add(x, y))

tensor([[ 2.0430,  0.8754,  1.0142],
        [ 0.3666, -0.9551,  3.2764],
        [ 1.4205, -1.1513, -0.0960],
        [ 2.6366,  0.1989,  0.7589],
        [-0.7611,  0.5044, -0.6390]])


Addition: providing an output tensor as argument



In [20]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.0430,  0.8754,  1.0142],
        [ 0.3666, -0.9551,  3.2764],
        [ 1.4205, -1.1513, -0.0960],
        [ 2.6366,  0.1989,  0.7589],
        [-0.7611,  0.5044, -0.6390]])


Addition: in-place



In [21]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 2.0430,  0.8754,  1.0142],
        [ 0.3666, -0.9551,  3.2764],
        [ 1.4205, -1.1513, -0.0960],
        [ 2.6366,  0.1989,  0.7589],
        [-0.7611,  0.5044, -0.6390]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [22]:
print(x[:, 1])

tensor([ 0.0317, -0.9887, -1.5360, -0.0040,  0.3053])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [26]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
print('------')
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
------
tensor([[-1.2022,  0.3071, -0.0906, -0.7261],
        [ 2.9056,  0.6205,  1.0150, -0.4897],
        [ 1.6664,  0.1533, -1.5700, -1.2025],
        [-0.1959,  0.2334,  2.2271,  1.0428]])
tensor([-1.2022,  0.3071, -0.0906, -0.7261,  2.9056,  0.6205,  1.0150,
        -0.4897,  1.6664,  0.1533, -1.5700, -1.2025, -0.1959,  0.2334,
         2.2271,  1.0428])
tensor([[-1.2022,  0.3071, -0.0906, -0.7261,  2.9056,  0.6205,  1.0150,
         -0.4897],
        [ 1.6664,  0.1533, -1.5700, -1.2025, -0.1959,  0.2334,  2.2271,
          1.0428]])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [27]:
x = torch.randn(1)
print(x)
print(x.item())

tensor(1.00000e-02 *
       [-9.0611])
-0.09061067551374435


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [28]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [29]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [30]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [31]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [34]:
torch.cuda.is_available()

False

In [32]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!